Repository w3c/wot-architecture, pull requests merged in 2022-05, with the labels that each got.

#746 Update Discoverer, add Registrant Definitions
  index.html
Labels: terminology

#749 Remove abnf validation from rel and op
  index.html
Labels: normative change

#754 terminology for orchestration
  index.html
Labels: terminology

#760 changing section level for MediaTypes
  index.html
Labels: editorial

#761 replacing placeholder for virtual thing with content
  index.html
Labels: by CR transition

#762 changing table style
  index.html
Labels: editorial

#768 Remove arch-id-correlation assertion
  index.html
Labels: normative change
