Repository w3c/wot-architecture, pull requests merged in 2022-03, with the labels that each got.

#711 Definitions for Device, Service, etc.
  index.html
Labels: ready to merge

#712 Terminology diagram as worked out on the Architecture call on Feb 17th
  proposals/WoT Things and relationships.drawio.svg
Labels: ready to merge

#700 Update Abstract
  index.html
Labels: ready to merge, non-normative

#713 Align the scripting interfaces in Architecture with the conformance classes in Scripting
  index.html
Labels: ready to merge

#695 fixes #688: Improving language, adding rfc2119 assertion
  index.html
Labels: normative change, normative section

#718 Add `data-lt` to a definition of Thing Model
  index.html
Labels: editorial

#704 restructuring lifecycle section
  index.html
Labels: non-normative-section

#721 Change "Thing Directory" to "Thing Description Directory"
  index.html
Labels: editorial

#720 Update list of editors
  index.html
Labels: editorial

#701 Update Implementation Report link in SOTD
  index.html
Labels: non-normative

#603 Define and Discuss "Hubs"
  index.html
Labels: non-normative
