Repository w3c/wot-architecture, pull requests merged in 2022-08, with the labels that each got.

#792 Chapter 9: editorial fixes
  index.html
Labels: editorial

#795 Address feedback from i18n group
  index.html
Labels: i18n

#813 fix links
  publication/ver11/2-wd/Overview.html
  publication/ver11/2-wd/index.html
  publication/ver11/2-wd/static.html
Labels: close
