Repository w3c/wot-architecture, pull requests merged in 2022-01, with the labels that each got.

#662 remove arch-uri-scheme
  index.html
Labels: normative change

#671 Add a figure of Thing Model
  images/architecture/thing_model_td.png
  images/architecture/thing_model_td.svg
  images/architecture/thing_model_td_inkscape.svg
  index.html
Labels: non-normative

#658 Improve section structure
  index.html
Labels: non-normative-section

#665 placeholder section on orchestration
  index.html
Labels: non-normative-section

#667 adding placeholder section for virtual things
  index.html
Labels: non-normative-section

#668 remove remove-arch-op-wellknown-compare assertion
  index.html
Labels: normative change

#677 removing table 1
  index.html
Labels: non-normative

#683 fix: some typos
  index.html
Labels: editorial
